flowchart LR
    Client[Browser / Nginx] --> Filter[SecurityHeaderFilter]
    Filter --> Interceptor[JwtAuthInterceptor]
    Interceptor --> Controller[Controller Layer]
    Controller --> Service[Service Layer]
    Service --> Mapper[MyBatis-Plus Mapper]
    Service --> JDBC[JdbcTemplate]
    Mapper --> MySQL[(MySQL)]
    JDBC --> MySQL
    Service --> Cache[(Spring Cache)]
    Controller --> Handler[GlobalExceptionHandler]
    Interceptor --> Handler
    Service --> Handler
