server:
  port: 8080

spring:
  profiles:
    active: prod # 默认激活开发环境配置
  application:
    name: dyx-blog
  datasource:
    url: jdbc:mysql://118.178.186.196:3306/dyx_blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: dyx_blog
    password: Dyx@blog
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id

logging:
  level:
    com.dyx.blog: info

jwt:
  secret: dyx-blog-secret-key-dyx-blog-secret-key
  expire-hours: 24

file:
  upload-path: uploads/
  access-prefix: /media/

dyx:
  security:
    cors-allowed-origins:
      - http://118.178.186.196
      - http://localhost:5173
      - http://127.0.0.1:5173
